name: Treat Wheel Zygisk CI

on:
  push:
    branches: [ main ]

  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NDK_PATH
        run: echo "NDK_PATH=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build with make
        env:
          IS_GITHUB_ACTION: true
        run: make

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: build/TreatWheel.zip
          archive: false